{
  "formatVersion": "1.1",
  "component": {
    "group": "AsmTrackDemo",
    "module": "AsmTrack",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-0.0.11.jar",
          "url": "asmtrack-0.0.11.jar",
          "size": 18263,
          "sha512": "7d970d6c8f04cdc194e9351c4e47f04f26308e5445647820b98f30ccbabc50b8b0abbb846449ac4e692406565590f082ef437a9ba0ccc2a4573dd609e4ea8330",
          "sha256": "aa080185ef1547b0e90739e42364f7a0c3c9942da23b2ae74281b1778bffa3ec",
          "sha1": "bd68f82df35489923de44e72168367eb3cc8b7cf",
          "md5": "6ffc1b84404346d6c4f30a5b4f8bc106"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-0.0.11.jar",
          "url": "asmtrack-0.0.11.jar",
          "size": 18263,
          "sha512": "7d970d6c8f04cdc194e9351c4e47f04f26308e5445647820b98f30ccbabc50b8b0abbb846449ac4e692406565590f082ef437a9ba0ccc2a4573dd609e4ea8330",
          "sha256": "aa080185ef1547b0e90739e42364f7a0c3c9942da23b2ae74281b1778bffa3ec",
          "sha1": "bd68f82df35489923de44e72168367eb3cc8b7cf",
          "md5": "6ffc1b84404346d6c4f30a5b4f8bc106"
        }
      ]
    }
  ]
}
