{
  "formatVersion": "1.1",
  "component": {
    "group": "AsmTrackDemo",
    "module": "AsmTrack",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "asmtrack-0.0.11.jar",
          "url": "asmtrack-0.0.11.jar",
          "size": 14052,
          "sha512": "1e748171f12cf25168b58aaaf05992abbd01c4578435ada11a62e2cb0b5f011e569ed2ad52129005b491d43879eec59d9ede808b6749d2ffd186227e3ff5259d",
          "sha256": "d87ef9c5745bc4d28f50dd75f5925506aec35444191823eea81f9557bf7b21de",
          "sha1": "9a482a283a1a824917f1f7ca818021030e520b44",
          "md5": "909a64ffde05a84542e78fd4a6852209"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-0.0.11.jar",
          "url": "asmtrack-0.0.11.jar",
          "size": 14052,
          "sha512": "1e748171f12cf25168b58aaaf05992abbd01c4578435ada11a62e2cb0b5f011e569ed2ad52129005b491d43879eec59d9ede808b6749d2ffd186227e3ff5259d",
          "sha256": "d87ef9c5745bc4d28f50dd75f5925506aec35444191823eea81f9557bf7b21de",
          "sha1": "9a482a283a1a824917f1f7ca818021030e520b44",
          "md5": "909a64ffde05a84542e78fd4a6852209"
        }
      ]
    }
  ]
}
