{
  "formatVersion": "1.1",
  "component": {
    "group": "plugin.asm.track",
    "module": "asmtrack",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "hpgdl5eoz5a6dpmainolwo23l4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "asmtrack-0.0.11.jar",
          "url": "asmtrack-0.0.11.jar",
          "size": 14731,
          "sha512": "df093b02bc77de53d1e36a36a1f4d43559e5eeb88ec24e1ffc9738a50a3cb7917f3db907e8bce8c7f92cbb2f1bd5944b721a6059b75da648118121fa52af1616",
          "sha256": "148c33be25e8581d21cc38378f9a548a08f10445fabfba3d21b95026146e9be9",
          "sha1": "7abfe01ef2f5de2a3b25dc5f3ac755a950a1332c",
          "md5": "25d519f4367d265332f86f96a76b97f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-0.0.11.jar",
          "url": "asmtrack-0.0.11.jar",
          "size": 14731,
          "sha512": "df093b02bc77de53d1e36a36a1f4d43559e5eeb88ec24e1ffc9738a50a3cb7917f3db907e8bce8c7f92cbb2f1bd5944b721a6059b75da648118121fa52af1616",
          "sha256": "148c33be25e8581d21cc38378f9a548a08f10445fabfba3d21b95026146e9be9",
          "sha1": "7abfe01ef2f5de2a3b25dc5f3ac755a950a1332c",
          "md5": "25d519f4367d265332f86f96a76b97f3"
        }
      ]
    }
  ]
}
