{
  "formatVersion": "1.1",
  "component": {
    "group": "AsmTrackDemo",
    "module": "AsmTrackPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-0.0.12.jar",
          "url": "asmtrack-0.0.12.jar",
          "size": 38020,
          "sha512": "76173912a8770330cd322e48040326851c497246ff00c63bfb65df44a779f6d6d7a697a367c5a8918489706535671436d5e861482d621545f651557575391de2",
          "sha256": "0a895e0d9d341c63049ea4fcf52af5807eb4bc3055c1b38f93a04dd1f5a589c7",
          "sha1": "c3b2632dbaf3e921c70c0244bc632ff2982b3046",
          "md5": "51aa27f53b16383111cb6f6ea1f6787d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-0.0.12.jar",
          "url": "asmtrack-0.0.12.jar",
          "size": 38020,
          "sha512": "76173912a8770330cd322e48040326851c497246ff00c63bfb65df44a779f6d6d7a697a367c5a8918489706535671436d5e861482d621545f651557575391de2",
          "sha256": "0a895e0d9d341c63049ea4fcf52af5807eb4bc3055c1b38f93a04dd1f5a589c7",
          "sha1": "c3b2632dbaf3e921c70c0244bc632ff2982b3046",
          "md5": "51aa27f53b16383111cb6f6ea1f6787d"
        }
      ]
    }
  ]
}
