{
  "formatVersion": "1.1",
  "component": {
    "group": "AsmTrackDemo",
    "module": "AsmTrackPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-0.0.12.jar",
          "url": "asmtrack-0.0.12.jar",
          "size": 29329,
          "sha512": "0af28855b4d1b60cc3e1ea717b8371cdbd06fb63c12d3b2dcac100e55295fff8737c8eda9b53913b998e743a86602c5c942f8f087aead7a5c235f942cf5a25bf",
          "sha256": "105b995dc354914d526111210331c555b9a094ab1e8471879d8da080f4b74e17",
          "sha1": "ffcbc768d4a6cc1988b0ec62ac2f53067e7ab36a",
          "md5": "14b2ca7f51f2ddffdc3d0e51f7c3edaf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-0.0.12.jar",
          "url": "asmtrack-0.0.12.jar",
          "size": 29329,
          "sha512": "0af28855b4d1b60cc3e1ea717b8371cdbd06fb63c12d3b2dcac100e55295fff8737c8eda9b53913b998e743a86602c5c942f8f087aead7a5c235f942cf5a25bf",
          "sha256": "105b995dc354914d526111210331c555b9a094ab1e8471879d8da080f4b74e17",
          "sha1": "ffcbc768d4a6cc1988b0ec62ac2f53067e7ab36a",
          "md5": "14b2ca7f51f2ddffdc3d0e51f7c3edaf"
        }
      ]
    }
  ]
}
