{
  "formatVersion": "1.1",
  "component": {
    "group": "AsmTrackDemo",
    "module": "AsmTrackPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-0.0.12.jar",
          "url": "asmtrack-0.0.12.jar",
          "size": 35514,
          "sha512": "6063805c395654cf9f132a0f0e2ea586a12eb30ed53b765e838b0ce1ffe49bb5ba51cd0299bc4127a4566de1fa720fbbdd79d763abb9aa2712d67a9cb24d9fc8",
          "sha256": "e94fcd2fc1f424df1eadfad5095861dc4332aedb42b87f75c6acef0240ce0147",
          "sha1": "b29e2c48fd1ed55e32d0e2230b60270d21bb31f8",
          "md5": "df28b249e72a30daf09f7632d183a8b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-0.0.12.jar",
          "url": "asmtrack-0.0.12.jar",
          "size": 35514,
          "sha512": "6063805c395654cf9f132a0f0e2ea586a12eb30ed53b765e838b0ce1ffe49bb5ba51cd0299bc4127a4566de1fa720fbbdd79d763abb9aa2712d67a9cb24d9fc8",
          "sha256": "e94fcd2fc1f424df1eadfad5095861dc4332aedb42b87f75c6acef0240ce0147",
          "sha1": "b29e2c48fd1ed55e32d0e2230b60270d21bb31f8",
          "md5": "df28b249e72a30daf09f7632d183a8b8"
        }
      ]
    }
  ]
}
