{
  "formatVersion": "1.1",
  "component": {
    "group": "plugin.asm.track",
    "module": "asmtrack",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "g5kjpxn2lbaajd52gy5rhv526q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "asmtrack-0.0.10.jar",
          "url": "asmtrack-0.0.10.jar",
          "size": 14744,
          "sha512": "4d2cb9b472f4e24d738bbcacf3e2262e4497326314603c91b3d26e235b69387bf0cc54dffeef43177f4cb8b9f7eb8de3700596bd39710d46d8f627c0f5236616",
          "sha256": "19c01b9887dc5f1291614267cd21caff7564521a340624a39401d56be20786a8",
          "sha1": "b83b8e37e5c5544bfaaf61a423c391627445957c",
          "md5": "e2118fe56205a8e38014f8e96a992540"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-0.0.10.jar",
          "url": "asmtrack-0.0.10.jar",
          "size": 14744,
          "sha512": "4d2cb9b472f4e24d738bbcacf3e2262e4497326314603c91b3d26e235b69387bf0cc54dffeef43177f4cb8b9f7eb8de3700596bd39710d46d8f627c0f5236616",
          "sha256": "19c01b9887dc5f1291614267cd21caff7564521a340624a39401d56be20786a8",
          "sha1": "b83b8e37e5c5544bfaaf61a423c391627445957c",
          "md5": "e2118fe56205a8e38014f8e96a992540"
        }
      ]
    }
  ]
}
