{
  "formatVersion": "1.1",
  "component": {
    "group": "AsmTrackDemo",
    "module": "AsmTrackPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-1.0.12.jar",
          "url": "asmtrack-1.0.12.jar",
          "size": 48940,
          "sha512": "1697546382c955846112f341e5c7058881be3872a3cd5265c62a01324e7d7566db4ae5f3c6b9254159e4f08bd36a5a8f6f69fef147dd5905978d16b54344cd9f",
          "sha256": "22a67ee90091ef35fec331b07d6ed3c6185bf0048c05fe09f97134150ded51d3",
          "sha1": "0b53a086f0646dcb47ba5da315886cf2a1303b5c",
          "md5": "b8c642632c19b7e96bffe955f3e8a6c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-1.0.12.jar",
          "url": "asmtrack-1.0.12.jar",
          "size": 48940,
          "sha512": "1697546382c955846112f341e5c7058881be3872a3cd5265c62a01324e7d7566db4ae5f3c6b9254159e4f08bd36a5a8f6f69fef147dd5905978d16b54344cd9f",
          "sha256": "22a67ee90091ef35fec331b07d6ed3c6185bf0048c05fe09f97134150ded51d3",
          "sha1": "0b53a086f0646dcb47ba5da315886cf2a1303b5c",
          "md5": "b8c642632c19b7e96bffe955f3e8a6c2"
        }
      ]
    }
  ]
}
