{
  "formatVersion": "1.1",
  "component": {
    "group": "AsmTraceDemo",
    "module": "AsmTrackPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-1.0.12.jar",
          "url": "asmtrack-1.0.12.jar",
          "size": 49016,
          "sha512": "2f0b9e4d1843ab23d98876fd7242a55d191e02a99109d058844925a9a7bebbc921c2a53526eff51a11d799fb687ad8170f98a624405c8bb4cc713d403b263c6e",
          "sha256": "3ebb380e0ffea2c84f0daa5470832d8a204377bb62e8a9791e4d51fbc6ddaef4",
          "sha1": "ba2f19f36232f4b4689bf3bbb79cdf8ecfdc6df7",
          "md5": "e37b2fb7f3dab5e9c6278974778625b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-1.0.12.jar",
          "url": "asmtrack-1.0.12.jar",
          "size": 49016,
          "sha512": "2f0b9e4d1843ab23d98876fd7242a55d191e02a99109d058844925a9a7bebbc921c2a53526eff51a11d799fb687ad8170f98a624405c8bb4cc713d403b263c6e",
          "sha256": "3ebb380e0ffea2c84f0daa5470832d8a204377bb62e8a9791e4d51fbc6ddaef4",
          "sha1": "ba2f19f36232f4b4689bf3bbb79cdf8ecfdc6df7",
          "md5": "e37b2fb7f3dab5e9c6278974778625b3"
        }
      ]
    }
  ]
}
