{
  "formatVersion": "1.1",
  "component": {
    "group": "AsmTrackDemo",
    "module": "AsmTrackPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-1.0.12.jar",
          "url": "asmtrack-1.0.12.jar",
          "size": 48935,
          "sha512": "d6bc3e87fab9f41da0199e098638e60cd0a0dcbd63d640a14800cf8e7e134db254d0f7b5d4c1b396c4c821556f4dcb03f435f79e63657684857d7459bb0a2490",
          "sha256": "fa5e3e97df8c4b45a1bdfe7cc0ad87def51925702e88ed5c8b6489c304d82eaa",
          "sha1": "7f00e5a3924a1d86e32a5119e1365e087d2842bd",
          "md5": "762cdbd058b10676d47d3c066fa8e81c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-1.0.12.jar",
          "url": "asmtrack-1.0.12.jar",
          "size": 48935,
          "sha512": "d6bc3e87fab9f41da0199e098638e60cd0a0dcbd63d640a14800cf8e7e134db254d0f7b5d4c1b396c4c821556f4dcb03f435f79e63657684857d7459bb0a2490",
          "sha256": "fa5e3e97df8c4b45a1bdfe7cc0ad87def51925702e88ed5c8b6489c304d82eaa",
          "sha1": "7f00e5a3924a1d86e32a5119e1365e087d2842bd",
          "md5": "762cdbd058b10676d47d3c066fa8e81c"
        }
      ]
    }
  ]
}
