{
  "formatVersion": "1.1",
  "component": {
    "group": "AsmTrace",
    "module": "AsmTrackPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-2.0.0.jar",
          "url": "asmtrack-2.0.0.jar",
          "size": 50071,
          "sha512": "305a06e386b95b2ca137322861990e8df4107ad872b05e78cba04ff2fe349d82270eea0046e14b6fe277d1b3af155bf7f379c2ef8084885d573bb1c00f805292",
          "sha256": "f4ac2c8deba9baa32d40ed311c018b2ebbb78953e7f8aea4d46bc0c22fa03e82",
          "sha1": "8d61a97a21246a820e91ed413717fd491ee85a5f",
          "md5": "9d7131bbbf217ad56a8807c3ff65717c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-2.0.0.jar",
          "url": "asmtrack-2.0.0.jar",
          "size": 50071,
          "sha512": "305a06e386b95b2ca137322861990e8df4107ad872b05e78cba04ff2fe349d82270eea0046e14b6fe277d1b3af155bf7f379c2ef8084885d573bb1c00f805292",
          "sha256": "f4ac2c8deba9baa32d40ed311c018b2ebbb78953e7f8aea4d46bc0c22fa03e82",
          "sha1": "8d61a97a21246a820e91ed413717fd491ee85a5f",
          "md5": "9d7131bbbf217ad56a8807c3ff65717c"
        }
      ]
    }
  ]
}
