{
  "formatVersion": "1.1",
  "component": {
    "group": "AsmTrackDemo",
    "module": "AsmTrackPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "AsmTrackPlugin-unspecified.jar",
          "url": "AsmTrackPlugin-unspecified.jar",
          "size": 46658,
          "sha512": "b3bbb919993c344f62a31e31c4bc28c263bc7cf71eb614ee09b8907039ad4bd19f94fe60d1d6530baa70db61fed92b02429ef02e5305c3c153b1297a2c66666e",
          "sha256": "0495fc77ad57b990fe4f538693e8d6a906557075756bf0ab6bfb31ce0deccf7b",
          "sha1": "af1245cecc9b6d361f9773626e80516b8fcf0929",
          "md5": "e2a7bd5001cdef212f1448ac84c0a6aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "AsmTrackPlugin-unspecified.jar",
          "url": "AsmTrackPlugin-unspecified.jar",
          "size": 46658,
          "sha512": "b3bbb919993c344f62a31e31c4bc28c263bc7cf71eb614ee09b8907039ad4bd19f94fe60d1d6530baa70db61fed92b02429ef02e5305c3c153b1297a2c66666e",
          "sha256": "0495fc77ad57b990fe4f538693e8d6a906557075756bf0ab6bfb31ce0deccf7b",
          "sha1": "af1245cecc9b6d361f9773626e80516b8fcf0929",
          "md5": "e2a7bd5001cdef212f1448ac84c0a6aa"
        }
      ]
    }
  ]
}
