{
  "formatVersion": "1.1",
  "component": {
    "group": "AsmTrackDemo",
    "module": "AsmTrackPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "AsmTrackPlugin-unspecified.jar",
          "url": "AsmTrackPlugin-unspecified.jar",
          "size": 46632,
          "sha512": "f799cfe6069c9401dc66be2720d1eb907954e913ae0724e96a63f80abeefa3c0fdf160c8ef1163dab2a4d61b552fdbad1a7f6bd509c922780ad4c6c512fc072d",
          "sha256": "c2f0edc590296bfa368d943daf65d87414fe9d550762b08fed8ab9f6722a66e4",
          "sha1": "7a059a148b2124e027affb39ece4bcced3c1201d",
          "md5": "1e52ad18f71bd5360fc4bd9341e12d3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "AsmTrackPlugin-unspecified.jar",
          "url": "AsmTrackPlugin-unspecified.jar",
          "size": 46632,
          "sha512": "f799cfe6069c9401dc66be2720d1eb907954e913ae0724e96a63f80abeefa3c0fdf160c8ef1163dab2a4d61b552fdbad1a7f6bd509c922780ad4c6c512fc072d",
          "sha256": "c2f0edc590296bfa368d943daf65d87414fe9d550762b08fed8ab9f6722a66e4",
          "sha1": "7a059a148b2124e027affb39ece4bcced3c1201d",
          "md5": "1e52ad18f71bd5360fc4bd9341e12d3b"
        }
      ]
    }
  ]
}
