{
  "formatVersion": "1.1",
  "component": {
    "group": "AsmTrackDemo",
    "module": "AsmTrackPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "AsmTrackPlugin-unspecified.jar",
          "url": "AsmTrackPlugin-unspecified.jar",
          "size": 46658,
          "sha512": "8c0c76528ed916cc6f8c4bb32805af398cc0948795f223a818114dcd59893b9a95091ab903d7497e27451afcd6ff6bd80da4e3d7fe06f725e9a8f628ce89ef1e",
          "sha256": "a078e517a0e4474df70f2e176972154096f0d4a23c5b99f8f289e7f4e4f7cf7b",
          "sha1": "803628177770d38ec67bcb2707bf2995c6bb31a5",
          "md5": "f3aeb1a1ff5f2526cb3c7d6deefc7df7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "AsmTrackPlugin-unspecified.jar",
          "url": "AsmTrackPlugin-unspecified.jar",
          "size": 46658,
          "sha512": "8c0c76528ed916cc6f8c4bb32805af398cc0948795f223a818114dcd59893b9a95091ab903d7497e27451afcd6ff6bd80da4e3d7fe06f725e9a8f628ce89ef1e",
          "sha256": "a078e517a0e4474df70f2e176972154096f0d4a23c5b99f8f289e7f4e4f7cf7b",
          "sha1": "803628177770d38ec67bcb2707bf2995c6bb31a5",
          "md5": "f3aeb1a1ff5f2526cb3c7d6deefc7df7"
        }
      ]
    }
  ]
}
