{
  "formatVersion": "1.1",
  "component": {
    "group": "plugin.asm.track",
    "module": "asmtrack",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "asmtrack-3.0.0.jar",
          "url": "asmtrack-3.0.0.jar",
          "size": 48346,
          "sha512": "8f3d10398948f976891928bf86bbe65c7e6d06e6ce289c4679f9f641169776fb7429ff0d37987a8ab6a34a528fd48478d796224925004af440f91013f2faec8a",
          "sha256": "8d4881b6b794e71ed007bb50c486ca173098c1f754485525c78227b53673d151",
          "sha1": "af360b2ffa5de725714edcaf2a355c720f5c3b8f",
          "md5": "2fe8be450b129d46375128419f5c23d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "asmtrack-3.0.0.jar",
          "url": "asmtrack-3.0.0.jar",
          "size": 48346,
          "sha512": "8f3d10398948f976891928bf86bbe65c7e6d06e6ce289c4679f9f641169776fb7429ff0d37987a8ab6a34a528fd48478d796224925004af440f91013f2faec8a",
          "sha256": "8d4881b6b794e71ed007bb50c486ca173098c1f754485525c78227b53673d151",
          "sha1": "af360b2ffa5de725714edcaf2a355c720f5c3b8f",
          "md5": "2fe8be450b129d46375128419f5c23d4"
        }
      ]
    }
  ]
}
